name: Предложение
description: Предложить новую функцию или улучшение
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Какую задачу это решает
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Предлагаемое решение
