import { initializeApp } from '/home/user/Wasatofficial-Shop-/functions/node_modules/firebase-admin/lib/app/index.js';
import { getFirestore } from '/home/user/Wasatofficial-Shop-/functions/node_modules/firebase-admin/lib/firestore/index.js';
import cfg from '/home/user/Wasatofficial-Shop-/firebase-applet-config.json';
import demo from '/tmp/claude-0/-home-user-Wasatofficial-Shop-/6ae9196d-6e10-572e-9337-53506395115c/scratchpad/current-demo.json';
initializeApp({ projectId: cfg.projectId });
const db = getFirestore(cfg.firestoreDatabaseId);
const src = (demo as any).PRODUCTS[0];
const p = JSON.parse(JSON.stringify({ ...src, id: 'p-first' }));
await db.doc('products/p-first').set(p);
await db.doc('settings/storefront').set({ categories: [{ id: src.category, name: 'Рубашки' }] }, { merge: true });
console.log('seeded one product');
process.exit(0);
